-- =======================================================================
-- SCRIPT DE ACTUALIZACIÓN DE BECAS (SUPABASE)
-- =======================================================================

-- 1. MANTENER SOLO 1 BECA (LA MÁS ANTIGUA) Y BORRAR EL RESTO
DELETE FROM public.becas 
WHERE id NOT IN (
    SELECT id FROM public.becas ORDER BY id LIMIT 1
);

-- 2. INSERTAR NUEVAS BECAS (REALES)
INSERT INTO public.becas (id, titulo, sponsor, cobertura, requisitos, fecha_cierre, nivel, icono, sobre, beneficios, afinidad, url_oficial) VALUES
('PAT-c99a2e', 'Becas BCP - Convocatoria 2026', 'Patronato BCP', 'Beca Integral (100%)', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado/Técnico', 'school', 'Beca de Pregrado/Técnico auspiciada por Patronato BCP.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, NULL),
('COM-de7366', 'Beca Fulbright - Convocatoria 2026', 'Comisión Fulbright', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Postgrado', 'school', 'Programa de Intercambio Educativo y Cultural entre Perú y Estados Unidos que fomenta futuros líderes en más de 140 países alrededor del mundo.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('PRO-0dd98d', 'Beca 18 - Convocatoria 2026', 'PRONABEC', 'Beca Integral (100%)', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por PRONABEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.pronabec.gob.pe/beca-18/'),
('DAA-9a0b72', 'Becas DAAD Alemania - Convocatoria 2026', 'DAAD', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Postgrado', 'school', 'Beca de Postgrado auspiciada por DAAD.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('PRO-c499e5', 'Beca Permanencia - Convocatoria 2026', 'PRONABEC', 'Beca Integral (100%)', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por PRONABEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.pronabec.gob.pe/beca-18/'),
('FUN-f96a5e', 'Becas Fundación Carolina - Convocatoria 2026', 'Fundación Carolina', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Postgrado', 'school', 'Beca de Postgrado auspiciada por Fundación Carolina.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('PRO-cca602', 'Beca Inclusión - Convocatoria 2026', 'PRONABEC', 'Beca Integral (100%)', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Técnico/Pregrado', 'school', 'Beca de Técnico/Pregrado auspiciada por PRONABEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.pronabec.gob.pe/beca-18/'),
('PRO-117848', 'Beca Técnico Productiva - Convocatoria 2026', 'PRONABEC', 'Beca Integral (100%)', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Técnico', 'school', 'Beca de Técnico auspiciada por PRONABEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.pronabec.gob.pe/beca-18/'),
('PRO-4ea5de', 'Beca Generación del Bicentenario - Convocatoria 2026', 'PRONABEC', 'Beca Integral (100%)', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Postgrado', 'school', 'Beca de Postgrado auspiciada por PRONABEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.pronabec.gob.pe/beca-18/'),
('PRO-141790', 'Beca Hijos de Docentes - Convocatoria 2026', 'PRONABEC', 'Beca Integral (100%)', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por PRONABEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.pronabec.gob.pe/beca-18/'),
('UPC-dec840', 'Beca de Honor UPC - Convocatoria 2026', 'UPC', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por UPC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('OEA-95525e', 'Becas OEA - Convocatoria 2026', 'OEA', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Postgrado', 'school', 'It looks like JavaScript is either disabled or turned off. Please enable JavaScript to correctly view this web site....', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('PUC-a272ca', 'Beca Lucet - Convocatoria 2026', 'PUCP', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por PUCP.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('CAM-041270', 'Beca Eiffel Francia - Convocatoria 2026', 'Campus France', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Postgrado', 'school', 'Beca de Postgrado auspiciada por Campus France.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('GOB-473094', 'Beca Vanier Canadá - Convocatoria 2026', 'Gobierno de Canadá', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Doctorado', 'school', 'We are no longer accepting applications for the Vanier Canada Graduate Scholarships. Please refer to the Canada Graduate Research Scholarship - Doctoral program web page for information regarding the ...', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('UPC-0952ea', 'Beca Excelencia UPCH - Convocatoria 2026', 'UPCH', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por UPCH.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('ALI-2fb8b4', 'Becas Alianza del Pacífico - Convocatoria 2026', 'Alianza del Pacífico', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Intercambio', 'school', 'XVII Convocatoria de la Plataforma de MovilidadEstudiantil y Académica de la Alianza del Pacífico 2026...', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('UTE-2f9537', 'Beca Mujeres en Ciencias - Convocatoria 2026', 'UTEC', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por UTEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('UTE-c0bfa8', 'Beca Talento UTEC - Convocatoria 2026', 'UTEC', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por UTEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('UNI-93224d', 'Beca Fe y Alegría - Convocatoria 2026', 'Universidad de Lima', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por Universidad de Lima.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('USI-f08637', 'Beca Fundador USIL - Convocatoria 2026', 'USIL', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por USIL.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('EMB-7d9370', 'Beca MEXT Japón - Convocatoria 2026', 'Embajada de Japón', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado/Postgrado', 'school', 'Beca de Pregrado/Postgrado auspiciada por Embajada de Japón.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('TEC-687654', 'Becas TECSUP - Convocatoria 2026', 'TECSUP', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Técnico', 'school', 'Beca de Técnico auspiciada por TECSUP.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('UNI-18f827', 'Beca Líderes con Propósito - Convocatoria 2026', 'Universidad del Pacífico', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por Universidad del Pacífico.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('UNI-5911f4', 'Beca Alto Rendimiento ESAN - Convocatoria 2026', 'Universidad ESAN', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por Universidad ESAN.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('UNI-7f8e14', 'Beca Talento UDEP - Convocatoria 2026', 'Universidad de Piura', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', '© 2026 UDEP. Todos los Derechos Reservados....', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('FUN-16a89c', 'Becas Campus Virtual Romero - Convocatoria 2026', 'Fundación Romero', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Cursos', 'school', 'Beca de Cursos auspiciada por Fundación Romero.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('UCV-35b3be', 'Beca Vallejiana - Convocatoria 2026', 'UCV', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por UCV.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('PRO-e6b5d0', 'Beca Deporte Escolar - Convocatoria 2026', 'PRONABEC', 'Beca Integral (100%)', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por PRONABEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.pronabec.gob.pe/beca-18/'),
('SEN-1b838d', 'Becas SENATI - Convocatoria 2026', 'SENATI', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Técnico', 'school', 'Beca de Técnico auspiciada por SENATI.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('GOB-8e91d3', 'Beca Chevening Perú - Convocatoria 2026', 'Gobierno UK', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Postgrado', 'school', 'Chevening Scholarships for Peruvians looking to study in the UK', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('NII-882638', 'Beca GKS Corea - Convocatoria 2026', 'NIIED', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado/Postgrado', 'school', 'The official portal for studying in Korea, operated by the Korean government. Information on studying in Korea, universities (language institutes), immigration procedures, student life, employment, and consultation.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85, 'https://www.gob.pe/pronabec'),
('beca-peru-2026', 'Beca Perú - Convocatoria 2026', 'PRONABEC', 'Cobertura parcial y total de costos académicos.', '{"nota_minima":14,"sisfoh":"Pobreza Extrema","tipo_colegio":"Público","requiere_mujeres":false}', '2026-07-08', 'Pregrado', 'school', 'La Beca Perú ofrece a jóvenes talentos la oportunidad de estudiar en instituciones privadas elegibles para fortalecer su educación superior.', '["Matrícula y pensiones de estudio","Materiales de estudio","Gastos de titulación"]'::jsonb, 85, 'https://www.pronabec.gob.pe/beca-peru/'),
('beca-continuidad-2026', 'Beca Continuidad de Estudios 2026', 'PRONABEC', 'Cobertura total de la pensión universitaria.', '{"nota_minima":12,"sisfoh":"Pobre","tipo_colegio":"Cualquiera","requiere_mujeres":false}', '2026-08-15', 'Pregrado', 'school', 'Programa diseñado para evitar la deserción de estudiantes de universidades e institutos públicos y privados.', '["Matrícula","Pensiones académicas","Manutención"]'::jsonb, 85, NULL),
('beca-cometa-2026', 'Beca Cometa - Convocatoria 2026', 'Intercorp', 'Cobertura del 100% para estudios universitarios en universidades de élite de EE.UU.', '{"nota_minima":16,"sisfoh":"Pobre","tipo_colegio":"Cualquiera","requiere_mujeres":false}', '2026-09-30', 'Pregrado', 'school', 'Beca Cometa es una iniciativa de Intercorp que busca formar a los futuros líderes del Perú brindándoles acceso a educación de clase mundial.', '["Matrícula en universidad Top EE.UU.","Pasajes aéreos","Seguro médico","Manutención y alojamiento"]'::jsonb, 85, 'https://www.becacometa.com'),
('beca-jovenes-bicentenario', 'Beca Jóvenes Bicentenario', 'Ministerio de Trabajo y Promoción del Empleo', 'Capacitación 100% gratuita para inserción laboral.', '{"nota_minima":null,"sisfoh":"Pobre","tipo_colegio":"Cualquiera","requiere_mujeres":false}', '2026-08-31', 'Técnico', 'school', 'Programa del Estado Peruano enfocado en potenciar la empleabilidad juvenil en los sectores productivos de mayor demanda.', '["Cursos gratuitos","Certificación oficial","Acompañamiento laboral"]'::jsonb, 85, 'https://www.gob.pe/mtpe'),
('beca-talento-pucp', 'Beca Talento PUCP', 'Pontificia Universidad Católica del Perú', 'Cobertura de derechos académicos según la escala socioeconómica asignada.', '{"nota_minima":15,"sisfoh":"Cualquiera","tipo_colegio":"Cualquiera","requiere_mujeres":false}', '2026-10-15', 'Pregrado', 'school', 'Reconoce el esfuerzo y el talento escolar de los estudiantes de secundaria a nivel nacional para ingresar a la PUCP.', '["Descuento o cobertura total de escalas de pago","Bono de libros","Asesoría académica personalizada"]'::jsonb, 85, 'https://www.pucp.edu.pe/becas'),
('beca-prociencia-2026', 'Beca de Investigación ProCiencia', 'CONCYTEC', 'Financiamiento de investigación y estipendio mensual.', '{"nota_minima":14,"sisfoh":"Cualquiera","tipo_colegio":"Cualquiera","requiere_mujeres":false}', '2026-07-30', 'Maestría', 'school', 'Auspiciada por CONCYTEC, apoya a los investigadores en desarrollo que contribuyen al avance científico del país.', '["Subvención mensual","Financiamiento de la investigación","Acceso a redes internacionales"]'::jsonb, 85, 'https://www.prociencia.gob.pe'),
('beca-loreal-unesco-peru', 'Beca L''Oréal-UNESCO Para las Mujeres en la Ciencia', 'L''Oréal Perú y CONCYTEC', 'Premio económico para la continuación de proyectos científicos.', '{"nota_minima":15,"sisfoh":"Cualquiera","tipo_colegio":"Cualquiera","requiere_mujeres":true}', '2026-08-20', 'Maestría', 'school', 'Reconocimiento a mujeres científicas sobresalientes para visibilizar y apoyar su labor en el desarrollo científico del país.', '["Premio económico directo","Reconocimiento nacional","Difusión del proyecto científico"]'::jsonb, 85, NULL),
('beca-ingles-access', 'Beca Inglés Access', 'Embajada de EE.UU. e ICPNA', 'Cobertura total del programa de estudios de idioma inglés por 2 años.', '{"nota_minima":14,"sisfoh":"Pobre","tipo_colegio":"Público","requiere_mujeres":false}', '2026-11-01', 'Idioma', 'school', 'Brinda fundamentos del idioma inglés y de la cultura estadounidense a estudiantes talentosos, abriendo oportunidades futuras.', '["Clases de inglés 100% financiadas","Materiales y libros","Campamentos y actividades extracurriculares"]'::jsonb, 85, 'https://pe.usembassy.gov/es/education-culture-es/access/'),
('becas-coursera-mtpe', 'Becas Coursera - Talento Digital', 'Ministerio de Trabajo / Google', 'Acceso gratuito a certificaciones de alto nivel.', '{"nota_minima":null,"sisfoh":"Cualquiera","tipo_colegio":"Cualquiera","requiere_mujeres":false}', '2026-12-15', 'Técnico', 'school', 'Alianza del MTPE para reducir la brecha tecnológica ofreciendo certificaciones avaladas por gigantes tecnológicos.', '["Acceso gratis a cursos premium en Coursera","Certificado oficial de Google/IBM","Bolsa de trabajo del MTPE"]'::jsonb, 85, NULL),
('beca-erasmus-peru', 'Becas Erasmus+ Mundus', 'Unión Europea', 'Financiamiento completo para maestrías conjuntas en Europa.', '{"nota_minima":15,"sisfoh":"Cualquiera","tipo_colegio":"Cualquiera","requiere_mujeres":false}', '2026-02-15', 'Maestría', 'school', 'Una de las becas internacionales más prestigiosas del mundo que permite estudiar posgrados en al menos dos países europeos.', '["Matrícula 100%","Mensualidad de 1000 - 1400 euros","Pasajes aéreos ida y vuelta","Seguro de viaje"]'::jsonb, 85, 'https://erasmus-plus.ec.europa.eu'),
('beca-excelencia-idat', 'Beca Excelencia Académica Idat', 'IDAT', 'Becas del 50% al 100% sobre la pensión mensual.', '{"nota_minima":15,"sisfoh":"Cualquiera","tipo_colegio":"Cualquiera","requiere_mujeres":false}', '2026-08-30', 'Técnico', 'school', 'Premia a los talentos escolares para iniciar estudios técnicos profesionales enfocados en tecnología y negocios.', '["Descuento en pensión mensual","Material didáctico online","Bolsa de empleo rápida"]'::jsonb, 85, 'https://www.idat.edu.pe'),
('beca-ensabap-2026', 'Beca para Artistas Destacados ENSABAP', 'Escuela Nacional Superior Autónoma de Bellas Artes del Perú', 'Cobertura de derechos académicos.', '{"nota_minima":13,"sisfoh":"Pobre","tipo_colegio":"Cualquiera","requiere_mujeres":false}', '2026-11-20', 'Pregrado', 'school', 'Brinda la posibilidad de desarrollar el talento artístico a los jóvenes con alta proyección visual y artística a nivel nacional.', '["Exoneración de pago de pensión","Acceso a talleres artísticos","Materiales seleccionados"]'::jsonb, 85, 'https://www.ensabap.edu.pe')
ON CONFLICT (id) DO UPDATE SET titulo = EXCLUDED.titulo, sponsor = EXCLUDED.sponsor, cobertura = EXCLUDED.cobertura, requisitos = EXCLUDED.requisitos, fecha_cierre = EXCLUDED.fecha_cierre, nivel = EXCLUDED.nivel, icono = EXCLUDED.icono, sobre = EXCLUDED.sobre, beneficios = EXCLUDED.beneficios, afinidad = EXCLUDED.afinidad, url_oficial = EXCLUDED.url_oficial;
