-- =======================================================================
-- SCRIPT DE ACTUALIZACIÓN DE BECAS (SUPABASE)
-- =======================================================================

-- 1. MANTENER SOLO 1 BECA (LA MÁS ANTIGUA) Y BORRAR EL RESTO
DELETE FROM public.becas 
WHERE id NOT IN (
    SELECT id FROM public.becas ORDER BY id LIMIT 1
);

-- 2. INSERTAR NUEVAS BECAS (REALES)
INSERT INTO public.becas (id, titulo, sponsor, cobertura, requisitos, fecha_cierre, nivel, icono, sobre, beneficios, afinidad) VALUES
('PAT-c99a2e', 'Becas BCP - Convocatoria 2026', 'Patronato BCP', 'Beca Integral (100%)', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado/Técnico', 'school', 'Beca de Pregrado/Técnico auspiciada por Patronato BCP.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('COM-de7366', 'Beca Fulbright - Convocatoria 2026', 'Comisión Fulbright', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Postgrado', 'school', 'Programa de Intercambio Educativo y Cultural entre Perú y Estados Unidos que fomenta futuros líderes en más de 140 países alrededor del mundo.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('PRO-0dd98d', 'Beca 18 - Convocatoria 2026', 'PRONABEC', 'Beca Integral (100%)', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por PRONABEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('DAA-9a0b72', 'Becas DAAD Alemania - Convocatoria 2026', 'DAAD', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Postgrado', 'school', 'Beca de Postgrado auspiciada por DAAD.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('PRO-c499e5', 'Beca Permanencia - Convocatoria 2026', 'PRONABEC', 'Beca Integral (100%)', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por PRONABEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('FUN-f96a5e', 'Becas Fundación Carolina - Convocatoria 2026', 'Fundación Carolina', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Postgrado', 'school', 'Beca de Postgrado auspiciada por Fundación Carolina.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('PRO-cca602', 'Beca Inclusión - Convocatoria 2026', 'PRONABEC', 'Beca Integral (100%)', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Técnico/Pregrado', 'school', 'Beca de Técnico/Pregrado auspiciada por PRONABEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('PRO-117848', 'Beca Técnico Productiva - Convocatoria 2026', 'PRONABEC', 'Beca Integral (100%)', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Técnico', 'school', 'Beca de Técnico auspiciada por PRONABEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('PRO-4ea5de', 'Beca Generación del Bicentenario - Convocatoria 2026', 'PRONABEC', 'Beca Integral (100%)', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Postgrado', 'school', 'Beca de Postgrado auspiciada por PRONABEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('PRO-141790', 'Beca Hijos de Docentes - Convocatoria 2026', 'PRONABEC', 'Beca Integral (100%)', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por PRONABEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('UPC-dec840', 'Beca de Honor UPC - Convocatoria 2026', 'UPC', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por UPC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('OEA-95525e', 'Becas OEA - Convocatoria 2026', 'OEA', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Postgrado', 'school', 'It looks like JavaScript is either disabled or turned off. Please enable JavaScript to correctly view this web site....', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('PUC-a272ca', 'Beca Lucet - Convocatoria 2026', 'PUCP', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por PUCP.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('CAM-041270', 'Beca Eiffel Francia - Convocatoria 2026', 'Campus France', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Postgrado', 'school', 'Beca de Postgrado auspiciada por Campus France.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('GOB-473094', 'Beca Vanier Canadá - Convocatoria 2026', 'Gobierno de Canadá', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Doctorado', 'school', 'We are no longer accepting applications for the Vanier Canada Graduate Scholarships. Please refer to the Canada Graduate Research Scholarship - Doctoral program web page for information regarding the ...', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('UPC-0952ea', 'Beca Excelencia UPCH - Convocatoria 2026', 'UPCH', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por UPCH.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('ALI-2fb8b4', 'Becas Alianza del Pacífico - Convocatoria 2026', 'Alianza del Pacífico', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Intercambio', 'school', 'XVII Convocatoria de la Plataforma de MovilidadEstudiantil y Académica de la Alianza del Pacífico 2026...', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('UTE-2f9537', 'Beca Mujeres en Ciencias - Convocatoria 2026', 'UTEC', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por UTEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('UTE-c0bfa8', 'Beca Talento UTEC - Convocatoria 2026', 'UTEC', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por UTEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('UNI-93224d', 'Beca Fe y Alegría - Convocatoria 2026', 'Universidad de Lima', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por Universidad de Lima.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('USI-f08637', 'Beca Fundador USIL - Convocatoria 2026', 'USIL', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por USIL.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('EMB-7d9370', 'Beca MEXT Japón - Convocatoria 2026', 'Embajada de Japón', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado/Postgrado', 'school', 'Beca de Pregrado/Postgrado auspiciada por Embajada de Japón.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('TEC-687654', 'Becas TECSUP - Convocatoria 2026', 'TECSUP', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Técnico', 'school', 'Beca de Técnico auspiciada por TECSUP.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('UNI-18f827', 'Beca Líderes con Propósito - Convocatoria 2026', 'Universidad del Pacífico', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por Universidad del Pacífico.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('UNI-5911f4', 'Beca Alto Rendimiento ESAN - Convocatoria 2026', 'Universidad ESAN', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por Universidad ESAN.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('UNI-7f8e14', 'Beca Talento UDEP - Convocatoria 2026', 'Universidad de Piura', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', '© 2026 UDEP. Todos los Derechos Reservados....', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('FUN-16a89c', 'Becas Campus Virtual Romero - Convocatoria 2026', 'Fundación Romero', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Cursos', 'school', 'Beca de Cursos auspiciada por Fundación Romero.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('UCV-35b3be', 'Beca Vallejiana - Convocatoria 2026', 'UCV', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por UCV.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('PRO-e6b5d0', 'Beca Deporte Escolar - Convocatoria 2026', 'PRONABEC', 'Beca Integral (100%)', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado', 'school', 'Beca de Pregrado auspiciada por PRONABEC.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('SEN-1b838d', 'Becas SENATI - Convocatoria 2026', 'SENATI', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Técnico', 'school', 'Beca de Técnico auspiciada por SENATI.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('GOB-8e91d3', 'Beca Chevening Perú - Convocatoria 2026', 'Gobierno UK', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Postgrado', 'school', 'Chevening Scholarships for Peruvians looking to study in the UK', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85),
('NII-882638', 'Beca GKS Corea - Convocatoria 2026', 'NIIED', 'Beca Parcial o Integral', '[{"campo":"Nacionalidad","valor":"Peruana"},{"campo":"Rendimiento","valor":"Tercio o Quinto Superior"},{"campo":"Condición","valor":"Evaluación socioeconómica o de excelencia"}]', '2026-11-30', 'Pregrado/Postgrado', 'school', 'The official portal for studying in Korea, operated by the Korean government. Information on studying in Korea, universities (language institutes), immigration procedures, student life, employment, and consultation.', '[{"nombre":"Cobertura de Pensión","icono":"school"},{"nombre":"Manutención / Estipendio","icono":"payments"},{"nombre":"Seguro de Salud","icono":"health_and_safety"}]'::jsonb, 85)
ON CONFLICT (id) DO UPDATE SET titulo = EXCLUDED.titulo, sponsor = EXCLUDED.sponsor, cobertura = EXCLUDED.cobertura, requisitos = EXCLUDED.requisitos, fecha_cierre = EXCLUDED.fecha_cierre, nivel = EXCLUDED.nivel, icono = EXCLUDED.icono, sobre = EXCLUDED.sobre, beneficios = EXCLUDED.beneficios, afinidad = EXCLUDED.afinidad;
